### ISSUE TITLE
Bug: Only highlighting the first included text instead of exact text.

### ISSUE THREAD

**Issue by rifkiard** [fayeed/flutter_mentions#116]
When there are two users with similar names, for example, rifki and rifkiard, and another user mentions "@rifkiard", the highlighted part is only "@rifki" instead of "@rifkiard".

https://github.com/fayeed/flutter_mentions/assets/49678787/e0a4c747-fd27-440b-9c53-1d790e710ef3

**Comment by maRci002** [comment]
One possible solution is to ensure that **rifkiard** appears before **rifki** in the `Mention.data` list. However, a downside of this approach is that the suggestion list also preserves the new ordering. The simplest solution is to sort the `Mention.data` by the `display` property.

To fix the issue [here](https://github.com/fayeed/flutter_mentions/blob/6fe2f0aa559765995d07ff84dfec05b91254b98a/lib/src/mention_view.dart#L271), the package should implement this sorting.

**Comment by maRci002** [comment]
Fix available #118:

```yaml
  flutter_mentions:
    git:
      url: https://github.com/fayeed/flutter_mentions.git
      ref: 87e13e5c7e912b9733e126a789254989de6b84c7
```
