### ISSUE TITLE
Generic mention

### ISSUE THREAD

**Issue by vasilich6107** [fayeed/flutter_mentions#54]
`Mention` does not have generic parameter type 
Something like `Mention<TData>` and accepts `Map<String, dynamic>` which does not allow to use code completion and static analysis inside `suggestionBuilder`

**Comment by maRci002** [comment]
Fix available #118:

```yaml
  flutter_mentions:
    git:
      url: https://github.com/fayeed/flutter_mentions.git
      ref: 85237c0a921d260341ec148bcc2c881284b9e5a5
```
