### ISSUE TITLE
maxLines is not nullable

### ISSUE THREAD

**Issue by ryanatev** [fayeed/flutter_mentions#59]
Trying to use the expands property which states that both maxLines and minLines must be null.  Unfortunately I am unable to set maxLines to null.  It is not a nullable property.

**Comment by thecaptainXgod** [comment]
Same here, it should be an easy task. Please add nullable.

**Comment by maRci002** [comment]
Fix available #118:

```yaml
  flutter_mentions:
    git:
      url: https://github.com/fayeed/flutter_mentions.git
      ref: 2ca30ff5e2e460065071e417fecffbe3993d9c0d
```
