### ISSUE TITLE
maxLines type

### ISSUE THREAD

**Issue by loic-hamdi** [fayeed/flutter_mentions#68]
Hi,

` final int maxLines;` should be ` final int? maxLines;` because both `minLines` and `maxLines` need to be set to null when `expands: true`

**Comment by maRci002** [comment]
Fix available #118:

```yaml
  flutter_mentions:
    git:
      url: https://github.com/fayeed/flutter_mentions.git
      ref: 2ca30ff5e2e460065071e417fecffbe3993d9c0d
```
