### ISSUE TITLE
Two Or More Of The Same Preposition Will Be Taken First

### ISSUE THREAD

**Issue by luffynas** [fayeed/flutter_mentions#70]
Bug Regex:

## Simulation:
Suggestion User Name
```
@Fay
@Fayeed
@Fayeed Pawaskar
```

##Bug
Tap `@Fayeed Pawaskar` on suggestion result will be `@Fay`

I suspect code in `RegExp('$_pattern'),` on file `AnnotationEditingController` line `71`

**Comment by xlDownxl** [comment]
Critical Bug for me too.

**Comment by maRci002** [comment]
Solution: https://github.com/fayeed/flutter_mentions/issues/116#issuecomment-2015992913

I can create a PR to avoid workaround

**Comment by maRci002** [comment]
Fix available #118:

```yaml
  flutter_mentions:
    git:
      url: https://github.com/fayeed/flutter_mentions.git
      ref: 87e13e5c7e912b9733e126a789254989de6b84c7
```
