### ISSUE TITLE
How we can implement pagination on mention list?

### ISSUE THREAD

**Issue by Rutu-02** [fayeed/flutter_mentions#91]

**Comment by maRci002** [comment]
#122 use `Mention.suggestionListBuilder` which gives you full control how to render suggestions, for instance you can add `CircularProgressIndicator` when you are fetching / paginating:

```yaml
  flutter_mentions:
    git:
      url: https://github.com/fayeed/flutter_mentions.git
      ref: 49d94534ecf4ee07f67920d1d743ce9963c8708d
```
